### ISSUE TITLE
Unable to change the position of a room

### ISSUE THREAD

**Issue by etiennepinchon** [resonance-audio/resonance-audio-web-sdk#5]
Hi!

Love Resonance, works great but it misses the ability to move a room in space (or maybe I missed something?). You can move the listener, you can move the source but not the room itself :(

Thanks,
Etienne

**Comment by drewbitllama** [comment]
Hi Etienne,

Since we do not support multiple rooms at the moment, we also don't support position the single room available. However, you can accomplish the mathematically identical result of positioning a room by <x,y,z> by subtracting that vector from the source and listener positions. 

Let me know if that helps.

Cheers,
Drew
