### ISSUE TITLE
Spatial audio does not work with audio streams

### ISSUE THREAD

**Issue by benank** [resonance-audio/resonance-audio-web-sdk#7]
I'm trying to use this as part of a voice chat feature in a game that implements CEF. However, it doesn't seem to apply any 3D effects to the voice stream. I tested a normal sound (ogg) and it worked as expected, with the audio becoming quieter as the player moved away from the other and the direction in the speakers changing as well. With an audio stream from a microphone, using `window.URL.createObjectURL(stream)` to get the source, it only plays the sound as if it were a normal sound - it doesn't matter where my player is in the game; the sound is the same volume and direction.

I'm curious as to if this even works with spatial audio. I tried using a different library (HowlerJS), but I read that audio streams are not supported with their spatial audio. Is this the same case here?

**Comment by drewbitllama** [comment]
Hi Benank,

I have a feeling you need to explicitly have WebAudio handle the stream via a createMediaStreamSource() function call and then pipe it's output to our renderer. See https://developer.mozilla.org/en-US/docs/Web/API/AudioContext/createMediaStreamSource for more details. 

Please feel free to post some example code as well so I can help you better. :)

Cheers,
Drew

**Comment by benank** [comment]
Hi, thank you for the response. Using `createMediaStreamSource` was exactly what I needed, along with muting the original audioElement. Thank you for your help!

**Comment by drewbitllama** [comment]
Excellent! So glad I could help. Let us know about what cool things you end
up making with our SDK. :)

Cheers,
Drew

**Comment by ryancwalsh** [comment]
@benank and @drewbitllama I'd be so appreciative if you could clarify what you did here because I have the same question [and shared my code in this other issue here](https://github.com/resonance-audio/resonance-audio-web-sdk/issues/34).

Like you said, regular wav files worked well, but I couldn't get webcam streams to work (even with `audioContext.createMediaStreamSource(video.srcObject);` ).

I'm wondering what you did differently to get it to work.

I realize it's 3.3 years later, but any hints you can think of would be much appreciated! Thanks!

**Comment by benank** [comment]
@ryancwalsh My use case was for a voice chat application, and the code is still available [here](https://github.com/benank/jc3mp-voice-chat/blob/spatial/client_package/ui/script.js#L33). I honestly can't give you much more than the code because I don't remember anything else about it at this point. Hope this helps!

**Comment by ryancwalsh** [comment]
@benank Wow, I didn't really expect that you'd respond at all, and the fact that you responded so quickly is blowing me away, especially given that you're sharing code.

I really appreciate it. 😃 

As it turns out, at the same time as you were typing this, I was able to figure it out based on your earlier hint: https://github.com/resonance-audio/resonance-audio-web-sdk/issues/34#issuecomment-819902221

Thank you so much!  This is really cool.
